version: '3.1'

services:

  productiondb:
    env_file: .env
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
    volumes:
      - productiondata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  productionvault:
    env_file: .env
    build: .
    restart: always
    ports:
      - 3001:3001
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      NODE_ENV: production
      PIPELINE_STAGE: ${PIPELINE_STAGE:?PIPELINE_STAGE}
    depends_on:
      - productiondb

volumes:
    productiondata: