version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
    volumes:
      - datavolume:/var/lib/postgresql/data

  vault:
    build: .
    restart: always
    ports:
      - 3001:3001
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      NODE_ENV: production
      PIPELINE_STAGE: ${PIPELINE_STAGE:?PIPELINE_STAGE}
    depends_on:
      - db
    
volumes:
    datavolume: